image: golang:1.13.1

cache:
  paths:
    - _GO/

stages:
  - test
  - metrics
  - build

before_script:
  - mkdir -p _GO
  - cp -R _GO $GOPATH
  - git submodule update --init --recursive
  - chmod +x ./make.sh
  - wget https://github.com/protocolbuffers/protobuf/releases/download/v3.9.2/protoc-3.9.2-linux-x86_64.zip
  - apt-get update
  - apt-get install unzip
  - unzip protoc-3.9.2-linux-x86_64.zip -d protoc
  - export PATH=$PATH:/`pwd`/protoc/bin
  - go get -u github.com/golang/protobuf/protoc-gen-go
  - protoc --proto_path=proto --proto_path=third_party --go_out=plugins=grpc:proto service.proto

unit_tests:
  stage: test
  script:
    - go test -coverprofile coverage.cov ./...
  artifacts:
    paths:
      - coverage.cov

code_coverage:
  stage: metrics
  script:
    - go get golang.org/x/tools/cmd/cover
    - go tool cover -html=coverage.cov -o coverage.html
  artifacts:
    paths:
      - coverage.html

build:
  stage: build
  script:
    - ./make.sh
  artifacts:
    paths:
      - distr/*

after_script:
  - cp -R $GOPATH ./_GO
  - echo "End CI"