image: golang:1.13.1

stages:
  - build
  - test
  - metrics

before_script:
  - git submodule update --init --recursive
  - chmod +x ./make.sh
  - wget https://github.com/protocolbuffers/protobuf/releases/download/v3.9.2/protoc-3.9.2-linux-x86_64.zip
  - apt-get update
  - apt-get install unzip
  - unzip protoc-3.9.2-linux-x86_64.zip -d protoc
  - export PATH=$PATH:/`pwd`/protoc/bin
  - go get -u github.com/golang/protobuf/protoc-gen-go
  - go get golang.org/x/tools/cmd/cover

unit_tests:
  stage: test
  script:
    - go test -coverprofile coverage.cov ./...

code_coverage:
  stage: metrics
  script:
    - go tool cover -html=coverage.cov -o coverage.html
  artifacts:
    paths:
      - coverage.html

build:
  stage: build
  script:
    - ./make.sh
  artifacts:
    paths:
      - distr/*

after_script:
  - echo "End CI"