image: unlucky/golang-protoc

stages:
  - build

before_script:
  - git submodule update --init --recursive
  - chmod +x ./make.sh

build:
  stage: build
  script:
    - ./make.sh
  artifacts:
    paths:
      - distr/*

after_script:
  - echo "End CI"