image: golang:1.13

stages:
  - build

before_script:
  - chmod +x ./make.sh

build:
  stage: build
  script:
    - ./make.sh
  artifacts:
    paths:
      - WncPlugin-linux-x64
      - WncPlugin-windows-x64.exe

after_script:
  - echo "End CI"