image: unlucky/golang-protoc

cache:
  paths:
    - _GO/

stages:
  - test
  - metrics
  - build

before_script:
  - mkdir -p _GO
  - cp -R _GO $GOPATH
  - git submodule update --init --recursive
  - chmod +x ./make.sh
  - go get github.com/golang/mock/mockgen
  - protoc --proto_path=proto --proto_path=third_party --go_out=plugins=grpc:proto service.proto
  - mockgen --source=proto/service.pb.go > mock/grpc_server_mock.go

unit_tests:
  stage: test
  script:
    - go test -coverprofile coverage.cov ./...
    - cp -R $GOPATH ./_GO
  artifacts:
    paths:
      - coverage.cov

code_coverage:
  stage: metrics
  script:
    - go get golang.org/x/tools/cmd/cover
    - go tool cover -html=coverage.cov -o coverage.html
  artifacts:
    paths:
      - coverage.html

build:
  stage: build
  script:
    - ./make.sh
  artifacts:
    paths:
      - distr/*

after_script:
  - echo "End CI"