name: Go

on: push

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.16
      uses: actions/setup-go@v2
      with:
        go-version: 1.16
      id: go

    - name: Install Protoc
      uses: arduino/setup-protoc@v1

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Pull all submodules
      run: git submodule update --init --remote --merge

    - name: Generate proto files
      run : |
        go get -u github.com/golang/protobuf/protoc-gen-go
        protoc --proto_path=proto --go_out=plugins=grpc:proto commands/commands.proto
        protoc --proto_path=proto --go_out=plugins=grpc:proto files/files.proto

    - name: Build
      run: go build
