name: Go

on: push

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.16
      uses: actions/setup-go@v2
      with:
        go-version: 1.16
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Pull all submodules
      run: git submodule update --init --remote --merge

    - name: Set up protobuf
      run: |
        wget https://github.com/protocolbuffers/protobuf/releases/download/v3.15.8/protoc-3.15.8-linux-x86_64.zip
        unzip protoc-3.15.8-linux-x86_64.zip -d $GITHUB_WORKSPACE/protoc
        echo "$GITHUB_WORKSPACE/protoc/bin" >> $GITHUB_PATH
        chmod +x $GITHUB_WORKSPACE/protoc/bin/protoc

    - name: Generate proto files
      run : |
        go get -u github.com/golang/protobuf/protoc-gen-go
        protoc --proto_path=proto --go_out=plugins=grpc:proto commands/commands.proto
        protoc --proto_path=proto --go_out=plugins=grpc:proto files/files.proto

    - name: Build
      run: |
        go mod download
        go build
