name: Go

on: push

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.14
      uses: actions/setup-go@v2.0.3
      with:
        go-version: 1.14
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
    
    - name: submodules-init
      uses: snickerbockers/submodules-init@v4
        
    - name: Set up protobuf
      run: |
        wget https://github.com/protocolbuffers/protobuf/releases/download/v3.11.4/protoc-3.11.4-linux-x86_64.zip
        unzip protoc-3.11.4-linux-x86_64.zip -d $GITHUB_WORKSPACE/protoc
        echo "::add-path::$GITHUB_WORKSPACE/protoc/bin"
        chmod +x $GITHUB_WORKSPACE/protoc/bin/protoc
        
    - name: Generate proto files
      run : |
        go get -u github.com/golang/protobuf/protoc-gen-go
        protoc --proto_path=proto --go_out=plugins=grpc:proto commands/commands.proto
        protoc --proto_path=proto --go_out=plugins=grpc:proto files/files.proto

    - name: Build 
      run: go build
