name: Go

on: push

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
    
    - name: submodules-init
      uses: snickerbockers/submodules-init@v4

    - name: Get dependencies
      run: |
        go get -v -t -d ./...
        if [ -f Gopkg.toml ]; then
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            dep ensure
        fi
        
    - name: Get protobuf
      run: |
        wget https://github.com/protocolbuffers/protobuf/releases/download/v3.11.4/protoc-3.11.4-linux-x86_64.zip
        unzip protoc-3.11.4-linux-x86_64.zip -d protoc
        echo "::add-path::$(pwd)/protoc/bin"
        go get -u github.com/golang/protobuf/protoc-gen-go
        echo $PATH
        
    - name: Generate Proto
      run: |
        protoc --proto_path=proto --go_out=plugins=grpc:proto commands/commands.proto
        protoc --proto_path=proto --go_out=plugins=grpc:proto files/files.proto

    - name: Build
      run: go build -v .
